---
# File: tasks/main.yml - Main tasks for Vault

- name: Include asserts
  include: asserts.yml

- name: "Add Vault user"
  user:
    name: "{{ vault_user }}"
    comment: "Vault user"
    group: "{{ vault_group }}"
    system: true
  when: vault_manage_user | bool

- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Check Vault installation
  command: which vault
  register: vault_installation
  changed_when: False
  ignore_errors: True
  check_mode: False

- name: Get installed Vault version
  shell: "{{ vault_installation.stdout }} -version | cut -d' ' -f2 | tr -d 'v'"
  when: not vault_installation is failed
  changed_when: False
  check_mode: False
  register: installed_vault_version

- name: Compute if installation is required
  set_fact:
    installation_required: "{{ vault_installation is failed or installed_vault_version.stdout != vault_version }}"

- name: Install OS packages and Vault Enterprise via control host
  include: install_enterprise.yml
  when:
    - vault_enterprise | bool
    - not vault_install_remotely | bool
    - installation_required | bool

- name: Install OS packages and Vault via control host
  include: install.yml
  when:
    - not vault_enterprise | bool
    - not vault_install_remotely | bool
    - installation_required | bool

- name: Install OS packages and Vault via remote hosts
  include: install_remote.yml
  when:
    - not vault_enterprise | bool
    - vault_install_remotely | bool
    - installation_required | bool

- name: Check Vault mlock capability
  command: "setcap -v cap_ipc_lock=+ep {{ vault_bin_path }}/vault"
  changed_when: False  # read-only task
  ignore_errors: True
  register: vault_mlock_capability

- name: Enable non root mlock capability
  command: "setcap cap_ipc_lock=+ep {{ vault_bin_path }}/vault"
  when: vault_mlock_capability is failed

- name: Create directories
  file:
    dest: "{{ item }}"
    state: directory
    owner: "{{ vault_user }}"
    group: "{{ vault_group}}"
  with_items:
    - "{{ vault_config_path }}"
    - "{{ vault_data_path }}"
    - "{{ vault_log_path }}"
    - "{{ vault_run_path }}"

- name: Enable logrotate for vault
  template:
    src: vault_logrotate.j2
    dest: /etc/logrotate.d/vault
    owner: root
    group: root
    mode: 0644
  when: vault_enable_logrotate

- name: TLS configuration
  include: ../tasks/tls.yml
  when: vault_tls_copy_certs == 0

- name: Listener configuration
  template:
    src: vault_listener.hcl.j2
    dest: "{{ vault_main_config }}"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: "0400"
  notify: Restart vault


- name: BSD init script
  template:
    src: vault_bsdinit.j2
    dest: /etc/rc.d/vault
    owner: root
    group: wheel
    mode: "0755"
  when: ansible_os_family == "FreeBSD"

- name: SYSV init script
  template:
    src: vault_sysvinit.j2
    dest: /etc/init.d/vault
    owner: root
    group: root
    mode: "0755"
  when:
    - not ansible_service_mgr == "systemd"
    - not ansible_os_family == "Debian"
    - not ansible_os_family == "FreeBSD"
    - not ansible_os_family == "Solaris"

- name: Debian init script
  template:
    src: vault_debian.init.j2
    dest: /etc/init.d/vault
    owner: root
    group: root
    mode: "0755"
  when:
    - not ansible_service_mgr == "systemd"
    - ansible_os_family == "Debian"
    - not ansible_os_family == "FreeBSD"
    - not ansible_os_family == "Solaris"

- name: systemd unit
  template:
    src: vault_systemd.service.j2
    dest: /lib/systemd/system/vault.service
    owner: root
    group: root
    mode: "0644"
  when:
    - ansible_service_mgr == "systemd"
    - not ansible_os_family == "FreeBSD"
    - not ansible_os_family == "Solaris"

- name: Start Vault
  service:
    name: vault
    state: started
    enabled: true

- name: Restart Vault if needed
  meta: flush_handlers
